### id: bgeeQ4
### handled by endpoint: http://biosoda.expasy.org:8080/rdf4j-server/repositories/bgeelight_postgres
### question: List the labels and identifiers of $$fruitfly$$ genes in bgee
PREFIX up: <http://purl.uniprot.org/core/>
PREFIX orth: <http://purl.org/net/orth#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
SELECT distinct ?gene ?geneName {
	?gene a orth:Gene .
	?gene rdfs:label ?geneName .
	?gene orth:organism ?taxon .
	?taxon obo:RO_0002162 ?species . #in taxon property .
	?species up:commonName ?commonName .
	FILTER ( lcase(str(?commonName)) = lcase("$$fruitfly$$") ) .
}
### this .rq file ist created by bioSODA rqWriter