### id: uniprotQ4
### handled by endpoint: https://sparql.uniprot.org/sparql
### question: Select all bacterial taxa, and their $$scientificname$$ from the UniProt taxonomy
PREFIX up: <http://purl.uniprot.org/core/>
PREFIX taxon: <http://purl.uniprot.org/taxonomy/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?taxon ?target WHERE {
	?taxon a up:Taxon .
	?taxon $$scientificname$$ ?target .
	?taxon rdfs:subClassOf taxon:2 .
}
$$innerlimit$$
### this .rq file ist created by bioSODA rqWriter