### id: bgeeQ2
### handled by endpoint: http://biosoda.expasy.org:8080/rdf4j-server/repositories/bgeelight_postgres
### question: Genes with the following term in the description: lung
PREFIX up: <http://purl.uniprot.org/core/>
PREFIX orth: <http://purl.org/net/orth#>
PREFIX dcterms: <http://purl.org/dc/terms/>
SELECT ?geneName ?geneId {
	?gene a orth:Gene .
	?gene rdfs:label ?geneName .
	?gene dcterms:identifier ?geneId .
	?gene dcterms:description ?desc .
	FILTER CONTAINS ( ?desc, 'lung' )
}
### this .rq file ist created by bioSODA rqWriter