### id: bgeeQ10
### handled by endpoint: http://biosoda.expasy.org:8080/rdf4j-server/repositories/bgeelight_postgres
### question: Anatomic entities at the $$mouse$$’s $$adult$$ stage where the $$apoc1$$ gene is expressed
PREFIX orth: <http://purl.org/net/orth#>
PREFIX up: <http://purl.uniprot.org/core/>
PREFIX genex: <http://purl.org/genex#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
SELECT DISTINCT ?anatEntity ?anatName {
	?seq a orth:Gene .
	?expr genex:hasSequenceUnit ?seq .
	?seq rdfs:label ?geneName .
	?expr genex:hasExpressionCondition ?cond .
	?cond genex:hasAnatomicalEntity ?anatEntity .
	?anatEntity rdfs:label ?anatName .
	?cond genex:hasDevelopmentalStage ?stage .
	?stage rdfs:label
	?stageName .
	?cond obo:RO_0002162 ?taxon . #in taxon property .
	?taxon up:commonName ?commonName .
	FILTER ( lcase(str(?commonName)) = lcase("$$mouse$$") ) .
	FILTER ( CONTAINS(?stageName,'$$adult$$') && LCASE(?geneName) = LCASE('$$apoc1$$') )
}
### this .rq file ist created by bioSODA rqWriter