### id: federatedOmaUniprotQ2
### handled by endpoint: http://biosoda.expasy.org:8890/sparql
### question: $$mouse$$'s proteins encoded by genes that are orthologous to $$rabbit$$'s $$HBBY$$ gene and their cross reference links to Uniprot
PREFIX lscr: <http://purl.org/lscr#>
PREFIX orth: <http://purl.org/net/orth#>
PREFIX up: <http://purl.uniprot.org/core/>
PREFIX obo: <http://purl.obolibrary.org/obo/>
SELECT DISTINCT ?PROTEIN_1 ?PROTEIN_2 ?UNIPROT_XREF_1 ?UNIPROT_XREF_2 WHERE {
	SERVICE <http://sparql.uniprot.org/sparql> {
		?taxon_1 up:commonName '$$mouse$$' .
		?taxon_2 up:commonName '$$rabbit$$' .
	}
	SERVICE <https://sparql.omabrowser.org/sparql> {
		?cluster a orth:OrthologsCluster .
		?cluster orth:hasHomologousMember ?node1 .
		?cluster orth:hasHomologousMember ?node2 .
		?node2 orth:hasHomologousMember* ?PROTEIN_2 .
		?node1 orth:hasHomologousMember* ?PROTEIN_1 .
		?PROTEIN_1 a orth:Protein .
		?PROTEIN_1 orth:organism/obo:RO_0002162 ?taxon_1 ;
			rdfs:label '$$HBBY$$' ;
			lscr:xrefUniprot ?UNIPROT_XREF_1 .
		?PROTEIN_2 a orth:Protein .
		?PROTEIN_2 orth:organism/obo:RO_0002162 ?taxon_2 .
		?PROTEIN_2 lscr:xrefUniprot ?UNIPROT_XREF_2 .
		FILTER ( ?node1 != ?node2 )
	}
}
### this .rq file ist created by bioSODA rqWriter