### id: omaQ3
### handled by endpoint: https://sparql.omabrowser.org/lode/sparql
### question: How many proteins (and their scientific name) per species are present in OMA database?
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX orth: <http://purl.org/net/orth#>
PREFIX up: <http://purl.uniprot.org/core/>
SELECT ?taxon ?target (COUNT(?protein) as ?Protein_count) WHERE {
	?protein a orth:Protein .
	?protein orth:organism ?organism .
	?inTaxon rdfs:label 'in taxon'@en .
	?organism ?inTaxon ?taxon .
	?taxon scientific name ?target .
}
GROUP BY ?taxon ?target
### this .rq file ist created by bioSODA rqWriter