### Id: Q12
### Handled by endpoint: http://biosoda.expasy.org:8890/sparql
### Question: Which are the genes in Human associated to a disease that are orthologous to a gene expressed in the rat’s brain?
### Query characteristics (BGP, basic graph pattern): 4 BGPs where all of them must be matched in a remote SPARQL endpoint (i.e.: SERVICE).  #BGP_1 = 6, #BGP_2 = 1, #BGP_3 ≥ 10, and #BGP_4 = 3. BGP_3  has  1 property path of length = 2 and 3 property paths of zero or more occurrences of orth:hasHomologousMember. It defines a constraint by using the FILTER() function.
### Number of results: 3
### Result example: http://omabrowser.org/ontology/oma#GENE_ENSRNOG00000000007	http://omabrowser.org/cgi-bin/gateway.pl?f=DisplayEntry&p1=HUMAN17852	http://purl.uniprot.org/uniprot/Q99259	The disease is caused by mutations affecting the gene represented in this entry.
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX genex: <http://purl.org/genex#>
PREFIX lscr: <http://purl.org/lscr#>
PREFIX orth: <http://purl.org/net/orth#>
PREFIX up: <http://purl.uniprot.org/core/>
SELECT DISTINCT ?gene ?OMA_LINK ?uniprot ?annotation_text WHERE {
	SERVICE <http://biosoda.expasy.org:8080/rdf4j-server/repositories/bgeelight_postgres> {
		SELECT DISTINCT ?gene ?id {
			?gene genex:isExpressedIn ?anat .
			?anat rdfs:label 'brain'^^xsd:string .
			?gene orth:organism ?o .
			?o obo:RO_0002162 ?taxon .
			?gene dcterms:identifier ?id .
			?taxon up:commonName 'rat' .
		}
		LIMIT 10
	}
	SERVICE <http://sparql.uniprot.org/sparql> {
		?taxon2 up:commonName 'Human' .
	}
	SERVICE <https://sparql.omabrowser.org/lode/sparql> {
		?protein2 a orth:Protein .
		?protein1 a orth:Protein .
		?cluster a orth:OrthologsCluster .
		?cluster orth:hasHomologousMember ?node1 .
		?cluster orth:hasHomologousMember ?node2 .
		?node2 orth:hasHomologousMember* ?protein2 .
		?node1 orth:hasHomologousMember* ?protein1 .
		?protein1 dcterms:identifier ?id .
		?protein2 rdfs:seeAlso ?OMA_LINK .
		?protein2 orth:organism/obo:RO_0002162 ?taxon2 .
		?protein2 lscr:xrefUniprot ?uniprot .
		FILTER ( ?node1 != ?node2 )
	}
	SERVICE <http://sparql.uniprot.org/sparql> {
		?uniprot up:annotation ?annotation .
		?annotation rdfs:comment ?annotation_text .
		?annotation a up:Disease_Annotation .
	}
}
### this .rq file ist created by bioSODA rqWriter (https://github.com/biosoda/bioquery/tree/master/rqWriter) - created at 2019-07-11 14:38:13