### Id: Q8
### Handled by endpoint: http://biosoda.expasy.org:8890/sparql
### Question: Genes expressed in the Human's pancreas and their annotations in UniProt.
### Query characteristics (BGP, basic graph pattern): 2 BGPs where all of them must be matched in a remote SPARQL endpoint (i.e.: SERVICE).  #BGP_1 = 6, and #BGP_2 = 4. BGP_2  has 1 property path of length = 2.
### Number of results: 58
### Result example: http://rdf.ebi.ac.uk/resource/ensembl/ENSG00000000003	http://purl.uniprot.org/uniprot/O43657	"N-linked (GlcNAc...) asparagine"
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX up: <http://purl.uniprot.org/core/>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX genex: <http://purl.org/genex#>
PREFIX lscr: <http://purl.org/lscr#>
PREFIX orth: <http://purl.org/net/orth#>
PREFIX up: <http://purl.uniprot.org/core/>
SELECT DISTINCT ?geneEns ?uniprot ?annotation_text {
	SERVICE <http://biosoda.expasy.org:8080/rdf4j-server/repositories/bgeelight_mysql> {
		SELECT ?geneEns {
			?geneB genex:isExpressedIn ?anat ;
				lscr:xrefEnsemblGene ?geneEns .
			?anat rdfs:label 'pancreas'^^xsd:string .
			?geneB orth:organism ?o .
			?o obo:RO_0002162 ?taxon2 .
			?taxon2 up:commonName 'Human' .
		}
		LIMIT 10
	}
	SERVICE <http://sparql.uniprot.org/sparql> {
		?uniprot rdfs:seeAlso / up:transcribedFrom ?geneEns .
		?uniprot up:annotation ?annotation .
		?annotation rdfs:comment ?annotation_text .
	}
}
### this .rq file ist created by bioSODA rqWriter (https://github.com/biosoda/bioquery/tree/master/rqWriter) - created at 2019-07-11 14:38:13