### id: uniprotQ2
### handled by endpoint: https://sparql.uniprot.org/sparql
### question: Select all UniProt proteins that were integrated on the $$date$$
PREFIX up: <http://purl.uniprot.org/core/>
SELECT ?protein WHERE {
	?protein a up:Protein .
	?protein up:created '$$date$$'^^xsd:date
}
$$innerlimit$$
### this .rq file ist created by bioSODA rqWriter