### id: uniprotQ7
### handled by endpoint: https://sparql.uniprot.org/sparql
### question: Select the preferred gene name and disease annotation of all human UniProt proteins that are known to be involved in a disease
PREFIX up: <http://purl.uniprot.org/core/>
PREFIX taxon: <http://purl.uniprot.org/taxonomy/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
SELECT ?name ?diseaseAnnotation WHERE {
	?protein a up:Protein .
	?protein up:organism human .
	?protein up:encodedBy ?gene .
	?gene skos:prefLabel ?name .
	?protein up:annotation ?annotation .
	?annotation a up:Disease_Annotation .
	?annotation rdfs:comment ?diseaseAnnotation .
}
### this .rq file ist created by bioSODA rqWriter