### id: uniprotQ1
### handled by endpoint: https://sparql.uniprot.org/sparql
### question: Select the UniProt protein with the mnemonic '$$A4HUMAN$$'
PREFIX up: <http://purl.uniprot.org/core/>
SELECT ?protein WHERE
{
	?protein a up:Protein .
	?protein up:mnemonic '$$A4HUMAN$$'
}
### this .rq file ist created by bioSODA rqWriter