### id: uniprotQ5
### handled by endpoint: https://sparql.uniprot.org/sparql
### question: which are the Ensembl transcript and genes for the $$A4HUMAN$$ protein 
PREFIX up: <http://purl.uniprot.org/core/>
SELECT * WHERE {
	?protein a up:Protein .
	?protein up:mnemonic '$$A4HUMAN$$' .
	?protein rdfs:seeAlso ?ensembl_Transcript .
	?ensembl_Transcript a up:Transcript_Resource .
	?ensembl_Transcript up:transcribedFrom ?ensembl_Gene .
	?ensembl_Transcript up:database <http://purl.uniprot.org/database/Ensembl> .
}
### this .rq file ist created by bioSODA rqWriter